name: GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.121.1"
          extended: true
          
      - name: Debug
        run: |
          echo "Current directory:"
          pwd
          echo "Directory structure:"
          ls -la
          echo "WebsiteRepo structure:"
          ls -la ./WebsiteRepo
          echo "Layouts directory:"
          ls -la ./WebsiteRepo/layouts
          echo "Partials directory:"
          ls -la ./WebsiteRepo/layouts/partials
          echo "Home partials:"
          ls -la ./WebsiteRepo/layouts/partials/home
          echo "Theme partials:"
          ls -la ./WebsiteRepo/themes/congo/layouts/partials/home
          echo "Hugo environment:"
          cd ./WebsiteRepo && hugo env

      - name: Build with explicit paths
        run: |
          cd ./WebsiteRepo
          hugo --minify --themesDir=./themes --layoutDir=./layouts --contentDir=./content
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: code-agree/code-agree.github.io
          publish_branch: main
          publish_dir: ./WebsiteRepo/public 