name: GitHub Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      - name: Verify Hugo Installation
        run: |
          hugo version
          which hugo

      - name: Compare Environment
        run: |
          echo "GitHub Actions Environment:"
          uname -a
          echo "Hugo version:"
          hugo version
          echo "Go version:"
          go version
          echo "Node.js version:"
          node -v
          echo "NPM version:"
          npm -v

      - name: Install dependencies
        run: |
          cd WebsiteRepo
          if [ -f "package.json" ]; then
            npm install
          fi

      - name: Build
        run: |
          cd WebsiteRepo
          echo "Current directory:"
          pwd
          echo "Current directory contents:"
          ls -la
          echo "Running Hugo build with verbose output:"
          HUGO_RESOURCEDIR="/tmp/hugo_cache" hugo --minify -v

      - name: Check generated files
        run: ls -R WebsiteRepo/public

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./WebsiteRepo/public