name: GitHub Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"

      - name: Verify Hugo Installation
        run: |
          hugo version
          which hugo

      - name: Debug - Show directory structure and search for config
        run: |
          echo "Root directory contents:"
          ls -la
          echo "WebsiteRepo directory contents:"
          ls -la WebsiteRepo
          echo "Searching for Hugo config files:"
          find . -name "config.toml" -o -name "config.yaml" -o -name "config.json"

      - name: Build
        run: |
          cd WebsiteRepo
          echo "Current directory:"
          pwd
          echo "Current directory contents:"
          ls -la
          echo "Running Hugo build:"
          hugo --minify --debug

      - name: Check generated files
        run: ls -R WebsiteRepo/public

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./WebsiteRepo/public