name: GitHub Pages Debug
on:
  push:
    branches:
      - main
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
          
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.121.1"
          extended: true
          
      - name: Debug File System
        run: |
          echo "Current directory:"
          pwd
          echo "Directory structure:"
          ls -la
          echo "WebsiteRepo structure:"
          ls -la ./WebsiteRepo
          echo "Layouts directory:"
          ls -la ./WebsiteRepo/layouts
          echo "Partials directory:"
          ls -la ./WebsiteRepo/layouts/partials
          echo "Home partials:"
          ls -la ./WebsiteRepo/layouts/partials/home
          echo "Theme directory:"
          ls -la ./WebsiteRepo/themes
          echo "Congo theme directory:"
          ls -la ./WebsiteRepo/themes/congo
          echo "Theme layouts directory:"
          ls -la ./WebsiteRepo/themes/congo/layouts
          echo "Theme partials directory:"
          ls -la ./WebsiteRepo/themes/congo/layouts/partials
          echo "Theme home partials:"
          ls -la ./WebsiteRepo/themes/congo/layouts/partials/home
          echo "Hugo environment:"
          cd ./WebsiteRepo && hugo env
          
      - name: Test Build
        run: |
          cd ./WebsiteRepo
          hugo --minify -v 